blank_issues_enabled: true
contact_links:
 - name: Bug Report Guidelines ğŸŒ
   url: https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
   about: Link to help you write a good bug report.
 - name: Documentation Link ğŸ“š
   url: https://github.com/SLINGhub/MSOrganiser/tree/master/docs
   about: Link to the documentation of this software.
 - name: Feature Request Guidelines ğŸŒ
   url: https://github.com/rstudio/rstudio/wiki/Writing-Good-Feature-Requests
   about: Link to help you write a good feature request.
 - name: General Question or Help â“ï¸
   url: https://github.com/SLINGhub/MSOrganiser/discussions
   about: If you wish to ask a general question, try out the Discussions section of this repository.
